$id: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/product-build.build.complete.json
$schema: http://json-schema.org/draft-07/schema#
title: productBuildComplete

description:
    Building of the product has been completed.
    This is a mandatory message.

properties:
    contact:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/contact.json
    run:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/run.json
    artifact:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/product-build.json
    build:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/build.json
    generated_at:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/common.json#/properties/generated_at
    version:
        $ref: file:///home/ariobolo/01WORKSPACE/04SOURCE/github/dater/pkg/schemas/fedora-ci/generated/common.json#/properties/version

required:
    - contact
    - run
    - artifact
    - generated_at
    - version

type: object